version: '2.1'

services:
  mysql:
    build: 
      context: .
      dockerfile: docker/mysql/Dockerfile
    healthcheck:
      test: "/usr/bin/mysql --user=root --password= --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
  node:
    build: 
      context: .
      dockerfile: docker/node/local.Dockerfile
    ports:
      - "7001:7001"
    depends_on:
      mysql:
        condition: service_healthy