# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: luckstar77/movie-server
      - image: circleci/node:8.11.2
      - image: docker:17.05.0-ce-git
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout:
          post:
            - git submodule sync
            - git submodule update --init


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      # - run: yarn install

      # - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test
      - run:
          name: Testing
          command: ls -al nodock
          # command: docker-compose -f nodock/docker-compose.yml -f nodock/docker-compose.test.yml run node
          # command: docker-compose -f nodock/docker-compose.yml -f nodock/docker-compose.test.yml run node
#  deploy:
#      docker:
#        - image: luckstar77/movie-server
#      steps:
#        - checkout
#        - run:
#            name: luckstar77-movie-server
#            command: |
#              git push https://heroku:e2f30f49-6fa2-414c-bb0f-c581771ae53c@git.heroku.com/luckstar77-movie-server.git master
